kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: srspvcfs
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-vpc-block-general-purpose