#!/bin/bash

ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 1 #needed warmup
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 1 |& tee OP_FWD/main_fwdPass_batch1.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 16 |& tee OP_FWD/main_fwdPass_batch16.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 32 |& tee OP_FWD/main_fwdPass_batch32.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 60 |& tee OP_FWD/main_fwdPass_batch60.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 64 |& tee OP_FWD/main_fwdPass_batch64.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 68 |& tee OP_FWD/main_fwdPass_batch68.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 128 |& tee OP_FWD/main_fwdPass_batch128.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 256 |& tee OP_FWD/main_fwdPass_batch256.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 512 |& tee OP_FWD/main_fwdPass_batch512.txt
ncu --profile-from-start off --metrics smsp__sass_thread_inst_executed_op_fadd_pred_on.sum,smsp__sass_thread_inst_executed_op_fmul_pred_on.sum,smsp__sass_thread_inst_executed_op_ffma_pred_on.sum   --target-processes all --print-summary per-kernel --csv python3 mainFwdProfiler.py --epochs 1 --batch-size 1024 |& tee OP_FWD/main_fwdPass_batch1024.txt
